### ISSUE TITLE
can´t push my lastest commits from local repo to Github

### ISSUE THREAD

**Issue by Elie-Soued** [Elie-Soued/Cv-Pilou#4]
This is the error that I am getting

![error](https://user-images.githubusercontent.com/65394404/82757691-73408780-9de2-11ea-9294-e323d828c74f.jpg)

**Comment by Elie-Soued** [comment]
All good. 
I had to pull on my pc le changes that were made remotely before pushing my commits to Github.

**Comment by joehakimrahme** [comment]
The reason you got this error is because you (most likely) did this on a new computer (or a new directory on your old computer):

1. `git init Cv-Pilou`
2. `git remote add githubRepo https://github.com/Elie-Soued/Cv-Pilou`
3. `git push githubRepo Master`

There's a shortcut to do:
1. `git init`
2. `git remote add`
3. `git pull`

This shortcut is called `git clone`. Next time if you want, you can simply `git clone https://github.com/Elie-Soued/Cv-Pilou` and all steps will be done automatically.
